// <auto-generated />
namespace myfoodapp.Hub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEventTypesPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEventTypesPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201808281124118_Add-Event-Types-Picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
