// <auto-generated />
namespace myfoodapp.Hub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOffice365Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOffice365Field));
        
        string IMigrationMetadata.Id
        {
            get { return "202009210740149_AddOffice365Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
